ALTER TABLE tbl_discord_leaguechannel
    ADD COLUMN GuildID BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER LeagueID,
    CHANGE COLUMN ChannelID ChannelID BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER GuildID,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (LeagueID, GuildID, ChannelID) USING BTREE;