import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon, FontAwesomeLayers, FontAwesomeLayersText } from '@fortawesome/vue-fontawesome';
import {
  faEnvelope,
  faGraduationCap,
  faHome,
  faList,
  faSpinner,
  faBell,
  faExternalLinkAlt,
  faBars,
  faTrophy,
  faUserFriends,
  faListOl,
  faDollarSign,
  faCircle as solidCircle,
  faCheck,
  faInfoCircle,
  faQuestionCircle,
  faUserPlus,
  faSignInAlt,
  faPlusCircle,
  faMoneyBillAlt,
  faMinusCircle,
  faSlash,
  faGamepad,
  faTimes,
  faUserCircle,
  faBookOpen,
  faUsers,
  faCalendarAlt,
  faCalendarDay,
  faExclamationCircle,
  faUserCog,
  faUser,
  faUserCheck,
  faCog,
  faExclamationTriangle,
  faAtom,
  faCircleNotch,
  faArchive
} from '@fortawesome/free-solid-svg-icons';

import {
  faCircle as regCircle,
  faSquare as regSquare,
} from '@fortawesome/free-regular-svg-icons';

import {
  faFontAwesome,
  faMicrosoft,
  faVuejs,
  faTwitterSquare,
  faRedditSquare,
  faGithubSquare,
  faFacebookSquare,
  faDiscord
} from '@fortawesome/free-brands-svg-icons';

library.add(
  faEnvelope,
  faGraduationCap,
  faHome,
  faList,
  faSpinner,
  faBell,
  faExternalLinkAlt,
  faBars,
  faTrophy,
  faUserFriends,
  faListOl,
  faDollarSign,
  faCheck,
  faInfoCircle,
  faQuestionCircle,
  faUserPlus,
  faSignInAlt,
  faPlusCircle,
  faMinusCircle,
  faFontAwesome,
  faMicrosoft,
  faVuejs,
  faTwitterSquare,
  faRedditSquare,
  regCircle,
  solidCircle,
  faSlash,
  faMoneyBillAlt,
  faGithubSquare,
  faGamepad,
  regSquare,
  faTimes,
  faFacebookSquare,
  faUserCircle,
  faBookOpen,
  faUsers,
  faCalendarAlt,
  faCalendarDay,
  faExclamationCircle,
  faExclamationTriangle,
  faUserCog,
  faUser,
  faUserCheck,
  faCog,
  faAtom,
  faCircleNotch,
  faDiscord,
  faArchive
);

export {
  FontAwesomeIcon,
  FontAwesomeLayers,
  FontAwesomeLayersText
};
