namespace FantasyCritic.DatabaseUpdater.CodeMigrations;

internal static class ProcessSetCleanupResources
{
    public static Dictionary<string, List<string>> OldGameNameMappings = new Dictionary<string, List<string>>()
        {
            {"Animal Crossing: New Horizons", ["Animal Crossing"]},
            {"Pokémon Sword and Shield", ["Pokemon Gen 8"]},
            {"Star Wars: Jedi Fallen Order", ["Star Wars Jedi: Fallen Order", "Star Wars:Jedi Fallen Order"]},
            {"Dying Light 2: Stay Human", ["Dying Light 2"]},
            {"Warcraft III: Reforged", ["Warcraft 3: Reforged"]},
            {"Metroid Prime 4: Beyond", ["Metroid Prime 4"]},
            {"Skull and Bones", ["Skull & Bones"]},
            {"Final Fantasy VII Remake", ["Final Fantasy 7 Remake"]},
            {"Little Town Hero", ["Town"]},
            {"APE OUT", ["Ape Out"]},
            {"The Dark Pictures: Man of Medan", ["Man of Medan"]},
            {"Marvel Ultimate Alliance 3: The Black Order", ["Marvel Ultimate Alliance 3"]},
            {"The Settlers: New Allies", ["The Settlers"]},
            {"SteamWorld Quest: Hand of Gilgamech", ["Steamworld Quest"]},
            {"Call of Duty: Modern Warfare (2019)", ["Call of Duty 2019"]},
            {"Dragon Ball Z Kakarot", ["Dragon Ball ‘Project Z’"]},
            {"Super Mario Maker 2", ["Super Mario Maker 2 (Unannounced)"]},
            {"Pikmin 4", ["Pikmin 4 (Unannounced)"]},
            {"Celeste: Farewell", ["Celeste DLC"]},
            {"Dead By Daylight (Switch)", ["Dead By Daylight"]},
            {"Chicory: A Colorful Tale", ["Drawdog"]},
            {"Trine 4: The Nightmare Prince", ["Trine 4"]},
            {"Solar Ash", ["Solar Ash Kingdom"]},
            {"GRID Autosport (Switch)", ["GRID Autosport"]},
            {"The Red Lantern", ["Red Lantern"]},
            {"Persona 5 Royal", ["Persona 5 The Royal"]},
            {"Power Rangers: Battle for the Grid", ["Power Raners: Battle for the Grid"]},
            {"Watch Dogs: Legion", ["Watch Dogs 3 (Unannounced)"]},
            {"ULTRABUGS", ["Vlambeer Arcade with ULTRABUGS"]},
            {"Shantae and the Seven Sirens (Console/PC)", ["Shantae 5"]},
            {"Darkwood (Console)", ["Darkwood"]},
            {"Splitgate", ["Splitgate Arena Warfare "]},
            { "HuniePop 2: Double Date", [""] },
            { "Baldo: The Guardian Owls", [""] },
            { "Brave Earth: Prologue", [""] },
            { "Disney Tsum Tsum Festival", [""] },
            { "The Witcher 3: Wild Hunt (Switch)", [""] },
            { "Spirit Hunter: NG", [""] },
            { "Medal of Honor: Above and Beyond", [""] },
            { "One Finger Death Punch 2 (Switch)", [""] },
            { "Paper Beast", [""] },
            { "The Legend of Zelda: Tears of the Kingdom", [""] },
            { "Senua's Saga: Hellblade II", [""] },
            { "Horizon Forbidden West", [""] },
            { "Diablo IV", [""] },
            { "Persona 5 Strikers", [""] },
            { "Vampire: The Masquerade - Bloodlines 2", [""] },
            { "The Wolf Among Us 2", [""] },
            { "Immortals: Fenyx Rising", [""] },
            { "12 Minutes", [""] },
            { "Tom Clancy’s Rainbow Six: Extraction", [""] },
            { "Dr. Kawashima’s Brain Training", [""] },
            { "Assassin's Creed Valhalla", [""] },
            { "Tokyo Mirage Sessions ♯FE: Encore", [""] },
            { "Call of Duty: Black Ops Cold War", [""] },
            { "Forza Motorsport", [""] },
            { "SkateBIRD", [""] },
            { "Fable", [""] },
            { "Impostor Factory", [""] },
            { "Iron Harvest", [""] },
            { "Gotham Knights", [""] },
            { "Paper Mario: The Origami King", [""] },
            { "Demon's Souls (2020)", [""] },
            { "Sakura Wars", [""] },
            { "Deltarune Chapter 2", [""] },
            { "Grand Theft Auto VI", [""] },
            { "Metroid Dread", [""] },
            { "Gran Turismo 7", [""] },
            { "Ratchet & Clank: Rift Apart", [""] },
            { "Mario Kart World", [""] },
            { "Amnesia: Rebirth", [""] },
            { "Hogwarts Legacy", [""] },
            { "Command & Conquer Remastered Collection", [""] },
            { "Call of Duty: Modern Warfare 2 Remastered", [""] },
            { "Crysis Remastered (Switch)", [""] },
            { "Super Mario Sunshine Remaster (Deprecated)", [""] },
            { "Werewolf: The Apocalypse - Earthblood", [""] },
            { "Dungeons & Dragons: Dark Alliance", [""] },
            { "Hitman 3", [""] },
            { "Gestalt: Steam & Cinder", [""] },
            { "New Mainline Banjo Kazooie (Unannounced)", [""] },
            { "Destruction Allstars", [""] },
            { "Resident Evil Village", [""] },
            { "Hyper Scape", [""] },
            { "Far Cry 6", [""] },
            { "Blue Protocol: Star Resonance", [""] },
            { "Worms Rumble", [""] },
            { "Bright Memory: Infinite", [""] },
            { "Suicide Squad: Kill the Justice League", [""] },
            { "Prince of Persia: The Sands of Time Remake", [""] },
            { "Super Mario 3D All-Stars", [""] },
            { "Cyanide & Happiness: Freakpocalypse", [""] },
            { "Balan Wonderworld", [""] },
            { "Ark 2", [""] },
            { "Dragon Age: The Veilguard", [""] },
            { "Battlefield 2042", [""] },
            { "Season: A Letter to the Future", [""] },
            { "Unannounced Mainline 3D Mario Platformer", [""] },
            { "Monster Hunter Rise", [""] },
            { "Final Fantasy XVI", [""] },
            { "The Forgotten City", [""] },
            { "The Lord of the Rings: Gollum", [""] },
            { "STALKER 2: Heart of Chornobyl", [""] },
            { "Forza Horizon 5", [""] },
            { "Rumored Metal Gear Solid 1 Remake (Unannounced)", [""] },
            { "Final Fantasy XIV: Endwalker", [""] },
            { "Unannounced New Mainline Ace Attorney Game", [""] },
            { "Spyro: A Realm Beyond", [""] },
            { "Pokémon Brilliant Diamond & Shining Pearl", [""] },
            { "Football Manager 2022", [""] },
            { "The Last of Us Multiplayer Game", [""] },
            { "Ghosts ‘n Goblins: Resurrection", [""] },
            { "Warhammer Age of Sigmar: Storm Ground", [""] },
            { "Call of Duty Vanguard", [""] },
            { "The Great Ace Attorney Chronicles", [""] },
            { "Path of Exile 2", [""] },
            { "The Legend of Zelda: Skyward Sword HD", [""] },
            { "Sonic Frontiers", [""] },
            { "Astro Bot", [""] },
            { "AEW: Fight Forever", [""] },
            { "The Elder Scrolls Online: Blackwood", [""] },
            { "God of War: Ragnarök", [""] },
            { "Figment 2: Creed Valley", [""] },
            { "Fire Emblem: Genealogy of the Holy War Re-Something (Unannounced)", [""] },
            { "007 First Light", [""] },
            { "Pokémon Let's Go 2 (Unannounced)", [""] },
            { "Final Fantasy VII Rebirth", [""] },
            { "Splatoon 3", [""] },
            { "Fire Emblem Engage", [""] },
            { "Re:ZERO -Starting Life in Another World- The Prophecy of the Throne", [""] },
            { "Indiana Jones and the Great Circle", [""] },
            { "Silent Hill f", [""] },
            { "eFootball", [""] },
            { "Endling - Extinction is Forever", [""] },
            { "Protodroid DeLTA", [""] },
            { "skate.", [""] },
            { "Stellar Blade", [""] },
            { "Metaphor: ReFantazio", [""] },
            { "The Legend of Heroes: Trails into Reverie", [""] },
            { "Resident Evil 4 Remake", [""] },
            { "Cosmodread", [""] },
            { "Forspoken", [""] },
            { "Diablo II Resurrected", [""] },
            { "Demon Slayer - Kimetsu no Yaiba - The Hinokami Chronicles", [""] },
            { "Star Wars Jedi: Survivor", [""] },
            { "Kingdom Come: Deliverance II", [""] },
            { "Mario + Rabbids: Sparks of Hope", [""] },
            { "2XKO", [""] },
            { "Assassin's Creed Infinity", [""] },
            { "EA Sports College Football 25", [""] },
            { "Untitled Playdead Game", [""] },
            { "Amid Evil: The Black Labyrinth", [""] },
            { "Shin-Chan: Me and the Professor on Summer Vacation", [""] },
            { "Aliens: Fireteam Elite", [""] },
            { "Life is Strange: True Colors", [""] },
            { "Star Wars Outlaws", [""] },
            { "Undisputed", [""] },
            { "OXENFREE II: Lost Signals", [""] },
            { "Star Wars: Knights of the Old Republic Remake", [""] },
            { "Lost Judgment", [""] },
            { "Phasmophobia", [""] },
            { "KitHack Model Club", [""] },
            { "Donkey Kong Bananza", [""] },
            { "The Legend of Heroes: Trails through Daybreak", [""] },
            { "Stranger of Paradise: Final Fantasy Origin", [""] },
            { "Dragon Quest III HD-2D Remake", [""] },
            { "Dragon Quest XII: Beyond Dreams", [""] },
            { "Xenoblade Chronicles 3", [""] },
            { "Marvel’s Midnight Suns", [""] },
            { "TOEM ", [""] },
            { "Vampire: The Masquerade - Bloodhunt", [""] },
            { "Advance Wars 1+2: Re-Boot Camp", [""] },
            { "Ghost of Tsushima Director's Cut", [""] },
            { "Dead Space (Remake)", [""] },
            { "NEEDY STREAMER OVERLOAD", [""] },
            { "XDefiant", [""] },
            { "Grand Theft Auto: The Trilogy – The Definitive Edition", [""] },
            { "Breakwaters: Crystal Tides", [""] },
            { "Firegirl: Hack 'n Splash Rescue", [""] },
            { "Stray Gods: The Roleplaying Musical", [""] },
            { "Replaced", [""] },
            { "Judas", [""] },
            { "F1 22", [""] },
            { "Call of Duty: Modern Warfare II", [""] },
            { "Slitterhead", [""] },
            { "Maximum Action", [""] },
            { "The Last of Us Part I", [""] },
            { "Velvet Bite: Softly, with Teeth", [""] },
            { "Towerborne", [""] },
            { "Kingdom Hearts IV", [""] },
            { "Gears of War: E-Day", [""] },
            { "Unforseen Incidents (Switch)", [""] },
            { "Sunset Overdrive Remaster (Unannounced)", [""] },
            { "Tony Hawk's Pro Skater 3 + 4", [""] },
            { "Persona 6", [""] },
            { "gen ATLAS", [""] },
            { "Goldeneye (Xbox One Re-Release)", [""] },
            { "Loco Motive", [""] },
            { "Like a Dragon: Infinite Wealth", [""] },
            { "The Witcher 3: Wild Hunt (PS5/Xbox Series)", [""] },
            { "FrighTV Presents GHOSTS", [""] },
            { "Chrono Cross: The Radical Dreamers Edition", [""] },
            { "Metal Gear Solid Δ: Snake Eater", [""] },
            { "Pokémon Scarlet & Violet", [""] },
            { "The First Descendant", [""] },
            { "SYNCED", [""] },
            { "Death Stranding Director's Cut (PC) ", [""] },
            { "EA Sports PGA Tour", [""] },
            { "Ace Combat 8: Wings of Theve", [""] },
            { "Grand Theft Auto V (PS5 & Xbox Series)", [""] },
            { "Deep Rock Galactic (Playstation Port)", [""] },
            { "Torchlight: Infinite", [""] },
            { "Metroid Prime Remastered", [""] },
            { "Detective Pikachu Returns", [""] },
            { "Armored Core VI: Fires of Rubicon", [""] },
            { "Dragon's Dogma 2", [""] },
            { "Deltarune", [""] },
            { "Lakeburg Legacies", [""] },
            { "Plants vs. Zombies 3: Welcome to Zomburbia", [""] },
            { "WRC Generations", [""] },
            { "Park Beyond", [""] },
            { "Marvel's Wolverine", [""] },
            { "Need for Speed Unbound", [""] },
            { "Resident Evil Village - Winters' Expansion", [""] },
            { "Just Dance 2023 Edition", [""] },
            { "System Shock 2: 25th Anniversary Remaster", [""] },
            { "F1 Manager 2022", [""] },
            { "Ashigaru: The Last Shogun", [""] },
            { "OD (Hideo Kojima Game)", [""] },
            { "FBC: Firebreak", [""] },
            { "Layers of Fear", [""] },
            { "Unannouced New S.O.C.O.M. Game", [""] },
            { "The Wreck", [""] },
            { "The Last Worker", [""] },
            { "Mortal Kombat 1", [""] },
        };

    private List<string> AllPossibleGameNames =
    [
        "12 Minutes",
        "13 Sentinels: Aegis Rim (Switch)",
        "13 Sentinels: Aegis Rim",
        "198X",
        "3 Minutes to Midnight™ - A Comedy Graphic Adventure",
        "30XX",
        "A Juggler's Tale",
        "A Memoir Blue",
        "A Plague Tale: Requiem",
        "A Space for the Unbound",
        "Abandoned",
        "Adios",
        "Advance Wars 1 + 2: Re-boot Camp",
        "Aerial_Knight's Never Yield",
        "Aeterna Noctis",
        "After The Fall",
        "Afterimage",
        "Afterlove EP",
        "Afterparty",
        "Age of Empires 4",
        "Age of Empires III: Definitive Edition",
        "Age of Wonders: Planetfall",
        "AI: The Somnium Files - nirvanA Initiative",
        "AI: The Somnium Files",
        "Aka",
        "Akatori",
        "Akiba's Trip: Hellbound & Debriefed ",
        "Alan Wake Remastered",
        "Alex Kidd in Miracle World DX",
        "Aliens: Fireteam Elite",
        "Aliens: Fireteam",
        "All Elite Wrestling: The Game",
        "Amid Evil: The Black Labrynth",
        "Amid Evil: The Black Labyrinth",
        "Amnesia: Rebirth",
        "Among Us VR",
        "An Airport for Aliens Currently Run by Dogs",
        "Ancestors: The Humankind Odyssey",
        "Ancient Dungeon VR",
        "Animal Crossing: New Horizons - Happy Home Paradise",
        "Animal Crossing: New Horizons",
        "Anno: Mutationem",
        "Anonymous;Code",
        "AO Tennis 2",
        "Ape Escape Game (Unannounced)",
        "Apparition",
        "Aragami 2",
        "ARC Raiders",
        "Arcadian Atlas",
        "Arctic Awakening",
        "Ark II",
        "Armored Core 6",
        "art of rally",
        "As Dusk Falls",
        "Ashwalkers",
        "Assassin's Creed 2020 (Unannounced)",
        "Assassin's Creed Infinity",
        "Assassin's Creed Valhalla",
        "Assassin’s Creed Valhalla: Dawn of Ragnarök",
        "Astral Chain",
        "Astria Ascending",
        "Astro's Playroom",
        "Atelier Mysterious Trilogy Deluxe Pack",
        "Atelier Ryza 2: Lost Legends and the Secret Fairy",
        "Atelier Ryza: Ever Darkness & the Secret Hideout",
        "Atelier Sophie 2",
        "Atomic Heart",
        "Attack of the Giant Crab",
        "Avatar: Frontiers of Pandora",
        "Avowed",
        "AWAY: The Survival Series",
        "Axiom Verge 2",
        "Aztech Forgotten Gods",
        "Azure Striker Gunvolt 3",
        "B.ARK",
        "Baby Storm",
        "Babylon's Fall",
        "Back 4 Blood",
        "Backbone",
        "BALAN WONDERWORLD",
        "Balan Wonderworld",
        "Baldo",
        "Baldo: The Guardian Owls",
        "Baldur's Gate 3",
        "Balsa Model Flight Simulator",
        "Battlefield 2042",
        "Battletoads",
        "Bayonetta & Vanquish 10th Anniversary Bundle",
        "Bayonetta 3",
        "Beacon Pines",
        "Bear and Breakfast",
        "Beard Blade",
        "Bendy and the Dark Revival",
        "Beyond a Steel Sky",
        "Beyond Good and Evil 2",
        "Biomutant",
        "Birushana: Rising Flower of Genpei",
        "Black Book",
        "Black Myth: Wukong",
        "Blacksad: Under the Skin",
        "Blacktail",
        "Blackwind",
        "Blair Witch",
        "Blasphemous",
        "Blaster Master Zero 3",
        "Blazing Chrome",
        "Bleeding Edge",
        "Blood Bowl 3",
        "Bloodroots",
        "Blossom Tales II: The Minotaur Prince",
        "Blue Fire",
        "Blue Protocol",
        "Bomb Rush Cyberfunk",
        "Boneworks",
        "Bonfire Peaks",
        "Book of Travels",
        "Boomerang X",
        "Borderlands 3",
        "Boundary",
        "Bowlbo: The Quest for Bing Bing",
        "Boyfriend Dungeon",
        "BPM: Bullets Per Minute",
        "Braid: Anniversary Edition",
        "Brave Earth - Prologue",
        "Bravely Default II",
        "Breakwaters",
        "Brewmaster: Beer Brewing Simulator",
        "Brigador Killers",
        "Brigandine: The Legend of Runersia",
        "Bright Memory infinite",
        "Bright Memory: Infinite",
        "Broken Roads",
        "Bubble Bobble 4 Friends",
        "Buddy Mission BOND",
        "Bugsnax",
        "Bugsnax: The Isle of BIGsnax",
        "Buildings Have Feelings Too!",
        "Bully 2 (Unannounced)",
        "Burden of Command",
        "Call of Duty 2020 (Unannounced)",
        "Call of Duty 2021",
        "Call of Duty Vanguard",
        "Call of Duty: Black Ops Cold War",
        "Call of Duty: Modern Warfare (2019)",
        "Call of the Sea",
        "Captain Tsubasa: Rise of New Champions",
        "Card Shark",
        "CARRION",
        "Cassette Beasts",
        "Celeste DLC",
        "Century: Age of Ashes",
        "Chained Echoes",
        "Chernobylite",
        "Chicken Police",
        "Chicory: A Colorful Tale",
        "Chinatown Detective Agency",
        "Chivalry 2",
        "Chocobo GP",
        "Choo-Choo Charles",
        "Chorus",
        "Chorus: An Adventure Musical",
        "Chrono Cross Remaster (Unannounced) ",
        "Circuit Superstars",
        "Cities VR",
        "Cities: Skylines - Airports",
        "Citizen Sleeper",
        "Clockwork Calamity in Mushroom World",
        "Code Vein",
        "Coffee Talk",
        "Cogen: Sword of Rewind",
        "Colossus Down",
        "Command & Conquer Remastered",
        "Company of Heroes 3",
        "Conan Chop Chop",
        "Concrete Genie",
        "Conscript",
        "Contra Rogue Corps",
        "Convergence: A League of Legends Story",
        "Cook, Serve, Delicious! 3?!",
        "Coral Island",
        "Coromon",
        "Cosmonious High",
        "Cosmophobia",
        "Cozy Grove",
        "Crash Bandicoot 4: It's About Time",
        "Crash Team Racing Nitro-Fueled",
        "Crayon Shin-Chan",
        "Creaks",
        "Creature in the Well",
        "Crimson Desert",
        "Cris Tales",
        "CrossfireX",
        "Crusader Kings 3 (Console)",
        "Crusader Kings III",
        "Crusader Kings III: Royal Court",
        "Crysis Remastered",
        "Cult of the Lamb",
        "Cultic",
        "Cuphead: The Delicious Last Course",
        "Curse of the Dead Gods",
        "Curse of the Sea Rats",
        "Cursed to Golf",
        "Cyber Shadow",
        "Cyberpunk 2077 Multiplayer Game",
        "Daemon x Machina",
        "Dakar Desert Rally",
        "Dandy Ace",
        "Danganronpa Decadence",
        "Danganronpa S: Ultimate Summer Camp",
        "Dark Alliance",
        "Dark Crystal: Age of Resistance Tactics",
        "Dark Deity",
        "Dark Pictures Anthology: Little Hope",
        "Darkest Dungeon 2",
        "Darksiders Genesis",
        "Dawn of the Monsters",
        "Dead Cells: Fatal Falls",
        "Dead Cells: The Queen and the Sea",
        "Dead Island 2",
        "Dead Space (Remake)",
        "Dead Static Drive",
        "Deadly Premonition 2: A Blessing in Disguise",
        "Death March Club",
        "Death Stranding Directors Cut (PC) ",
        "Death Stranding",
        "Death Stranding: Director’s Cut",
        "Death Trash",
        "Deathloop",
        "Deathverse: Let it Die",
        "Death’s Door",
        "Deep Rock Galactic (Console)",
        "Definitely Not Fried Chicken",
        "Deltarune (Full Release)",
        "Deltarune Chapter 2",
        "Deltarune",
        "Demon Slayer - Kimetsu no Yaiba - The Hinokami Chronicles",
        "Demon Slayer: Kimetsu no Yaiba – Hinokami Kepputan",
        "Demon Souls Remake (Unannounced) ",
        "Demon Souls Remake",
        "Demon Throttle",
        "Demon Turf",
        "Dennaton Games Untitled New Game",
        "Desperados III",
        "Despot's Game",
        "Destiny 2: Beyond Light",
        "Destiny 2: Lightfall",
        "Destiny 2: Shadowkeep",
        "Destiny 2: The Final Shape",
        "Destiny 2: The Witch Queen",
        "Destroy All Humans! 2 - Reprobed",
        "Destroy All Humans!",
        "Destruction Allstars ",
        "Detective Pikachu Sequel (Unannounced)",
        "Diablo 4",
        "Diablo II Remake",
        "Diablo II Resurrected",
        "Diablo Immortal",
        "Die by the Blade",
        "Digimon Survive",
        "Diplomacy is Not an Option",
        "DiRT5",
        "Disciples: Liberation",
        "Disco Elysium: The Final Cut",
        "Disgaea 6: Defiance of Destiny",
        "Disintegration",
        "Disjunction",
        "Disney Tsum Tsum",
        "Distant Worlds 2",
        "Divinity: Fallen Heroes",
        "DNF Duel",
        "DokeV",
        "Doki Doki Literature Club +",
        "Dolmen",
        "Donut Dodo",
        "Doom 3: VR Edition",
        "DOOM Eternal: The Ancient Gods - Part Two",
        "Doraemon: Story of Seasons",
        "Dordogne",
        "Dorfromantik",
        "Dr Kawashima's Brain Training (Brain Age) for Nintendo Switch",
        "Dragon Age 4",
        "Dragon Ball Z Kakarot",
        "Dragon Ball: The Breakers",
        "Dragon Quest Builders 2",
        "Dragon Quest III HD-2D",
        "Dragon Quest XII: The Flames of Fate",
        "Dragon's Dogma 2 (Unannounced)",
        "Dragonball Z Kakarot",
        "Dreams",
        "Dune: Spice Wars",
        "Dungeons & Dragons: Dark Alliance",
        "Dustborn",
        "Dwarf Fortress (Steam Release)",
        "Dying Light 2",
        "Dying Light 2: Stay Human",
        "Dynasty Warriors 9 Empires",
        "Dyson Sphere Program",
        "EA Sports PGA TOUR (2022)",
        "Earth Defense Force 6",
        "Earth Defense Force: World Brothers",
        "Earthblade",
        "Earthbreakers",
        "Eastward",
        "Echo Generation",
        "eFootball",
        "Eiyuden Chronicle: Rising",
        "El Hijo",
        "Elden Ring",
        "Eldest Souls",
        "Elex II",
        "Elite Dangerous: Odyssey",
        "Eliza",
        "Emily is Away <3",
        "Empire of Sin",
        "Ender Lilies: Quietus of the Knights",
        "Endless Dungeon",
        "Endling - Extinction is Forever",
        "Endling",
        "eSports Boxing Club",
        "Euro Truck Simulator 2 - Heart of Russia",
        "Everhood",
        "EVERSPACE 2",
        "Everwild",
        "Evil Dead: The Game",
        "Evil Genius 2: World Domination",
        "Evil West",
        "Exo One",
        "ExoMecha",
        "Expeditions: Rome",
        "F.I.S.T.: Forged In Shadow Torch",
        "F1 (2021)",
        "F1 2019",
        "F1 2020",
        "F1 2022",
        "F1 Management Game",
        "Fable (Unannounced)",
        "Fable (Xbox Series X)",
        "Factorio",
        "Fae Tactics",
        "Fairy Tail",
        "FAITH: The Unholy Trinity",
        "Fall Guys: Ultimate Knockout",
        "Fallen Aces",
        "Falling Frontier",
        "Famicom Detective Club: The Girl Who Stands Behind",
        "Famicom Detective Club: The Missing Heir",
        "Fantasian",
        "Far Cry 6 (Unannounced)",
        "Far Cry 6",
        "Far: Changing Tides",
        "Farming Simulator 23",
        "Fashion Police Squad",
        "Fast and Furious: Crossroads",
        "Fatal Frame: Maiden of Black Water",
        "Field of Glory II: Medieval",
        "FIFA 20",
        "FIFA 21",
        "FIFA 22",
        "FIFA 23",
        "Fight Knight",
        "Fights in Tight Spaces",
        "Figment 2: Creed Valley",
        "Figment: Creed Valley",
        "Filament",
        "Final Fantasy 7 Remake",
        "Final Fantasy Crystal Chronicles Remastered Edition",
        "Final Fantasy IV Pixel Remaster",
        "Final Fantasy Origin",
        "Final Fantasy V Pixel Remastered",
        "Final Fantasy VI Pixel Remaster",
        "Final Fantasy VII Ever Crisis",
        "Final Fantasy VII Remake Part 2",
        "Final Fantasy VII Remake: Intergrade",
        "Final Fantasy XIV: Endwalker",
        "Final Fantasy XIV: Shadowbringers",
        "Final Fantasy XVI ",
        "Fire Emblem: Geneaology of the Holy War Remake (Unannounced)",
        "Fire Emblem: Three Houses – Cindered Shadows",
        "Fire Emblem: Three Houses",
        "Firegirl",
        "Firegirl: Hack 'n Splash Rescue",
        "Firmament",
        "Fisti-Fluffs",
        "Five Nights at Freddy's: Security Breach",
        "Flashback 2",
        "Floppy Knights",
        "Football Manager (2021)",
        "Football Manager 2021",
        "Football Manager 2022",
        "Football Manager 2023",
        "Forgotten City",
        "Forspoken",
        "Forspoken: In Tanta We Trust",
        "Forza Horizon 5 (Unannounced)",
        "Forza Horizon 5",
        "Forza Motorsport (Xbox Series X)",
        "Forza Motorsport 8 (Unannounced)",
        "Freakpocalypse: The Cyanide & Happiness Adventure Game",
        "Freedom Planet 2",
        "Freshly Frosted",
        "Frog Detective 3: Corruption at Cowboy County",
        "Frogun",
        "Frostpunk 2",
        "Fuga: Melodies of Steel",
        "Furries & Scalies & Scarecrows OH MY!",
        "FurstDate: A Furry Dating Simulator ",
        "Fuser",
        "Galahad 3093",
        "Game Builder Garage",
        "Gamedec",
        "Garden Story",
        "Garlic",
        "Gears 5",
        "Gears 6 (Unannounced)",
        "Gears Tactics",
        "GenDesign's Untitled New Game",
        "Genesis Noir",
        "Genshin Impact",
        "Gerda: A Flame in Winter",
        "Gestalt Steam and Cinder",
        "Gestalt: Steam & Cinder",
        "Get In The Car, Loser!",
        "Ghost of Tsushima Director's Cut",
        "Ghost of Tsushima Standalone Expansion (Rumoured)",
        "Ghost of Tsushima",
        "Ghost Recon Breakpoint",
        "Ghost Song",
        "Ghost ‘n Goblins: Resurrection",
        "Ghostrunner",
        "Ghostrunner: Project_Hel",
        "Ghosts",
        "GhostWire Tokyo",
        "Gigabash",
        "Glitched",
        "Gloomwood",
        "Gnosia",
        "God of War (PC)",
        "God of War: Ragnarok",
        "God of War: Ragnarök",
        "Godfall",
        "Gods & Monsters",
        "Going Medieval",
        "Goldeneye (Rumored Rerelease)",
        "Goodbye Volcano High",
        "Gord",
        "Gotham Knights",
        "Gran Turismo 7",
        "Gran Turismo Sequel (Unannounced)",
        "Granblue Fantasy Versus",
        "Granblue Fantasy: Relink",
        "Grand Theft Auto 6 (Unannounced)",
        "Grand Theft Auto Remastered",
        "Grand Theft Auto V (PS5)",
        "Grand Theft Auto: The Trilogy – The Definitive Edition",
        "Grapple Dog",
        "GRAVEN",
        "Greak: Memories of Azur",
        "Greedfall",
        "GRID Legends",
        "GRID",
        "Griftlands",
        "GRIME",
        "Grounded ",
        "Growbot",
        "GTFO",
        "Guild Wars 2: End of Dragons",
        "Guilty Gear Strive",
        "Gungrave G.O.R.E.",
        "Gunvolt Chronicles: Luminous Avenger iX 2",
        "Gunvolt Chronicles: Luminous Avenger iX",
        "Hades",
        "Half Life: Alyx",
        "Halo Infinite",
        "Happy Game",
        "Hardspace: Shipbreaker",
        "Harold Halibut",
        "Harry Potter (Unannounced WB Games)",
        "Harvest Moon One World",
        "Hatsune Miku: Project DIVA Mega Mix",
        "Haunted Chocolatier",
        "Have a Nice Death",
        "Haven",
        "Hazel Sky",
        "Hazelnut Bastille",
        "Heavenly Bodies",
        "Hell Pie",
        "Hello Neighbor 2",
        "Hero's Hour",
        "Hindsight 20/20",
        "Hindsight",
        "Hitman 3 (Partially Announced)",
        "Hitman 3",
        "Hoa",
        "Hogwarts Legacy",
        "Hokko Life",
        "Hollow Knight: Silksong",
        "Homeworld 3",
        "Honey, I Joined a Cult",
        "Hood: Outlaws and Legends",
        "Horizon Call of the Mountain",
        "Horizon Forbidden West",
        "Horizon: Zero Dawn Sequel (Unannounced)",
        "Hot Wheels Unleashed",
        "Humanity",
        "Humankind",
        "Hundred Days - Winemaking Simulator",
        "HuniePop 2",
        "HuniePop 2: Double Date",
        "Hyper Scape (Rumored)",
        "Hyrule Warriors: Age of Calamity",
        "Hytale",
        "I Am Dead",
        "I Am Jesus Christ",
        "I Expect You To Die 2: The Spy and the Liar ",
        "I Was a Teenage Exocolonist",
        "Icarus",
        "Idolmaster Starlit Season",
        "Ikai",
        "Ikenfell",
        "Ilysia",
        "IMMORTALITY",
        "Immortals Fenyx Rising - Myths of the Eastern Realm",
        "Immortals: Fenyx Rising",
        "Imposter Factory",
        "Impostor Factory",
        "In Sound Mind",
        "In the Valley of Gods",
        "Indivisible",
        "Industries of Titan",
        "Infernax",
        "Injustice 3 (Unannounced)",
        "Inkulinati",
        "Inscryption",
        "Iron Corbo: Kung Fu Janitor",
        "Iron harvest ",
        "Iron Harvest",
        "It Takes Two",
        "Itorah",
        "Jack Move",
        "Jackbox Party Pack 7",
        "Jenny LeClue",
        "JETT: The Far Shore",
        "Journey to the Savage Planet",
        "Judgment Sequel (Rumored)",
        "Judgment",
        "Jurassic World: Evolution 2",
        "Just Dance 2020",
        "Just Dance 2022",
        "Just Dance 23",
        "Kaiju Wars",
        "Kao the Kangaroo",
        "KartRider: Drift",
        "Kaze and the Wild Masks",
        "Kena: Bridge of Spirits",
        "Kentucky Route Zero TV Edition",
        "Kerbal Space Program 2",
        "KeyWe",
        "Kill la Kill the Game: IF",
        "Killer Queen Black",
        "Kimetsu no Yaiba: Hinokami Keppuutan",
        "King Arthur: Knight's Tale",
        "King of Seas",
        "King's Bounty II",
        "Kingdom Come: Deliverance 2 (Unannounced)",
        "Kingdom Hearts III Re:Mind",
        "Kingdom Hearts: Melody of Memory",
        "Kingdoms of Amalur: Re-Reckoning - Fatesworn",
        "Kingdoms of the Dump",
        "Kirby and the Forgotten Land",
        "Knights of Honor II: Sovereign",
        "Knockout City",
        "Know By Heart",
        "Kraken Academy!!",
        "Lab Rat",
        "Lake",
        "Lakebury Legacies",
        "Last Epoch",
        "Last of Us Factions 2",
        "Last Stop",
        "Lawn Mowing Simulator",
        "Layton's Mystery Journey: Katrielle and the Millionaires' Conspiracy",
        "League of Legends MMO",
        "League of Legends: Wild Rift",
        "Legend of Mana Remaster",
        "Legends of Runeterra",
        "Lego Star Wars: The Skywalker Saga",
        "Lemnis Gate",
        "Liberated",
        "Life is Strange 3",
        "Life is Strange Remastered Collection",
        "Life is Strange: True Colors",
        "Lil Gator Game",
        "Little Devil Inside",
        "Little Kitty, Big City",
        "Little Nightmares 2",
        "Little Town Hero",
        "Little Witch in the Woods",
        "Loco Motive ",
        "Lone Echo 2",
        "Loop Hero",
        "Loot River",
        "Lord of the Rings: Gollum",
        "Lost Ark",
        "Lost Eidolons",
        "Lost Ember",
        "Lost in Random",
        "Lost Judgment",
        "Lost Judgment: The Kaito Files",
        "Lost Soul Aside",
        "Low-Fi",
        "Luigi's Mansion 3",
        "LUNA The Shadow Dust",
        "LUNARK",
        "Madden 20",
        "Madden 21",
        "Madden 22 ",
        "Madden NFL 23",
        "Mafia: Definitive Edition",
        "Magic: Legends",
        "Makai Kingdom: Reclaimed and Rebound",
        "Man of Medan",
        "Maneater",
        "Manifold Garden",
        "Maquette",
        "Mario & Sonic at the Olympic Games Tokyo 2020",
        "Mario + Rabbids: Sparks of Hope",
        "Mario and Rabbids Sequel (Unannounced)",
        "Mario Golf: Super Rush",
        "Mario Kart (Unannounced Next Mainline Console Game)",
        "Mario Kart 9 (Unannounced)",
        "Mario Kart Live: Home Circuit",
        "Mario Party Superstars",
        "Martha is Dead",
        "Marvel Ultimate Alliance 3: The Black Order",
        "Marvel XCOM Style Game",
        "Marvel's Avengers (Square Enix)",
        "Marvel's Guardians of the Galaxy",
        "Marvel's Iron Man VR",
        "Marvel’s Midnight Suns",
        "Marvel’s Wolverine",
        "Mass Effect: Legendary Edition",
        "MAXIMUM ACTION",
        "MechWarrior 5: Mercenaries",
        "Medal of Honor: Above and Beyond",
        "MediEvil",
        "Mega Man Zero/ZX Legacy Collection ",
        "Melty Blood: Type Lumina",
        "Metal Gear Solid Snake Eater Remake (Unannounced)",
        "Metal Slug Tactics",
        "Metal Wolf Chaos XD",
        "Metal: Hellsinger",
        "Metroid Dread",
        "Metroid Prime 1 HD (Unannounced)",
        "Metroid Prime 4",
        "Metroid Prime Trilogy HD (Unannounced)",
        "Microsoft Flight Simulator (Xbox Series X)",
        "Microsoft Flight Simulator",
        "Microsoft Flight Simulator: Top Gun Maverick",
        "Midnight Fight Express",
        "Miitopia",
        "Mind Scanners",
        "Minecraft: Dungeons",
        "Mineko's Night Market",
        "Minoria",
        "Minute of Islands",
        "Miss Kobayashi’s Dragon Maid: Sakuretsu!! Chorogon Breath",
        "MLB The Show 20",
        "MLB The Show 21",
        "MLB The Show 22",
        "Modern Warfare 2 Remastered (Unannounced)",
        "Monark",
        "Mondo Museum",
        "Monster Harvest",
        "Monster Hunter Rise (PC)",
        "Monster Hunter Rise",
        "MONSTER HUNTER RISE",
        "Monster Hunter Rise: Sunbreak",
        "Monster Hunter Stories 2: Wings of Ruin",
        "Monster Hunter World: Iceborne",
        "Moonglow Bay",
        "Mortal Kombat 12 (Unannounced)",
        "Mortal Shell",
        "Mosaic",
        "Moss: Book II",
        "Mount & Blade II: Bannerlord",
        "Moving Out",
        "MultiVersus",
        "Munchkin: Quacked Quest",
        "Mundaun",
        "Murder By Numbers",
        "My Friend Pedro",
        "My Friend Peppa Pig",
        "N1RV Ann-A: Cyberpunk Bartender Action",
        "NAIAD",
        "Naraka: Bladepoint",
        "Narita Boy",
        "NBA 2K21",
        "NBA 2k22",
        "NBA 2K23",
        "NCAA Football Reboot",
        "Nebuchadnezzar",
        "Necrobarista",
        "Necromunda: Hired Gun",
        "Need For Speed: Hot Pursuit Remastered",
        "NEEDY GIRL OVERDOSE",
        "NEEDY STREAMER OVERLOAD",
        "Nekojishi: Lin & Partners",
        "NEO: The World Ends with You",
        "Neon White",
        "Neurodeck: Psychological Deckbuilder",
        "Neverwinter nights: Enhanced Edition (Console)",
        "New Banjo Kazooie  (Unannounced)",
        "New Bioshock Game (Unannounced)",
        "New Fire Emblem Game (Unannounced)",
        "New Fire Emblem Game (Unnanounced)",
        "New Pokémon Snap",
        "New World",
        "New Xenoblade Game (Unannounced)",
        "Next Frictional Game",
        "Next Gen Battlefield Game",
        "Next Gilson B Pontes Game",
        "NG",
        "NHL 20",
        "NHL 21",
        "NHL 22",
        "NHL 23",
        "Nickelodeon All-Star Brawl",
        "NieR Replicant ver.1.22474487139",
        "Night Call",
        "Nighthawks",
        "Nightingale",
        "Ninja Gaiden: Master Collection",
        "Nioh 2",
        "No More Heroes 3",
        "No Place for Bravery",
        "No Straight Roads",
        "Nobody Saves the World",
        "NORCO",
        "Not For Broadcast",
        "Nour: Play With Your Food",
        "Nova Drift",
        "NUTS",
        "Nykra",
        "Ocean's Heart",
        "Oddworld: Soulstorm",
        "Odin: Valhalla Rising",
        "Olija",
        "OlliOlli World",
        "Omno",
        "OMORI",
        "One Finger Death Punch 2",
        "One Lonely Outpost",
        "One Night Stand (Consoles)",
        "One Piece Pirate Warriors 4",
        "One Step From Eden",
        "One-Punch Man: A Hero Nobody Knows",
        "ONINAKI",
        "Ooblets",
        "Open Roads",
        "Ori and the Will of the Wisps",
        "Ori: The Collection",
        "Out There: Oceans of Time",
        "Outer Wilds: Echoes of the Eye",
        "Outriders",
        "Overland",
        "Overwatch 2",
        "Oxenfree 2: Lost Signals",
        "Palia",
        "Palworld",
        "Panzer Corps 2",
        "Panzer Dragoon Voyage Record",
        "Panzer Dragoon: Remake",
        "Panzer Paladin",
        "Paper Beast",
        "Paper Beasts",
        "Paper Mario Sequel (Unannounced)",
        "Paper Mario: The Origami King",
        "Papetura",
        "Paradise Lost",
        "Paradise Marsh",
        "Paranoia: Happiness is Mandatory",
        "Park Beyond ",
        "Party Animals",
        "Path of Exile II",
        "Pathfinder: Wrath of the Righteous (Console)",
        "Pathfinder: Wrath of the Righteous",
        "Patrick's Parabox",
        "Peaky Blinders: Mastermind",
        "Peglin",
        "Pentiment",
        "Perfect Dark",
        "Persona 4 Arena Ultimax",
        "Persona 5 Royal",
        "Persona 5 Scramble: The Phantom Strikers",
        "Persona 5 Strikers",
        "Persona 5 The Royal",
        "Persona 6 (Unannounced)",
        "PES 2022",
        "PGA Tour 2K21",
        "Phantasy Star Online 2",
        "Phantasy Star Online 2: New Genesis",
        "Phantom Abyss",
        "Phantom Breaker: Omnia",
        "Phantom Brigade",
        "Phantom: Covert Ops",
        "Pharaoh: A New Era",
        "Phasmaphobia",
        "Phoenix Point",
        "Phoenix Wright: Ace Attorney 7",
        "Phogs",
        "Pigeon Simulator",
        "Pikmin 3 Deluxe",
        "Pikmin 4 (Unannounced)",
        "Pinball FX",
        "Pistol Whip",
        "Pistol Whip: Smoke & Thunder",
        "PixelJunk Eden 2",
        "Planet of Lana",
        "Planet Zoo",
        "Plants vs Zombies 3",
        "Please Be Happy",
        "Pocky & Rocky Reshrined",
        "Pokemon Diamond and Pearl Remake (Unannounced)",
        "Pokemon Let's Go 2 (Unannounced)",
        "Pokemon Unite",
        "Pokemon: The Isle of Armor",
        "Pokémon Brilliant Diamond & Shining Pearl",
        "Pokémon Generation 9",
        "Pokémon Legends Arceus",
        "Pokémon Let's Go 2 (Unannounced)",
        "Pokémon Mystery Dungeon: Rescue Team DX",
        "Pokémon Trading Card Game Live",
        "Police Stories",
        "Potion Craft: Alchemist Simulator",
        "Praey for the Gods",
        "Predator: Hunting Grounds",
        "Prince of Persia: The Sands of Time Remake",
        "Pro Evolution Soccer 2021",
        "Prodeus",
        "Project 007 (IO Interactive)",
        "Project Athia",
        "Project Belfry (Stoic)",
        "Project Cars 3",
        "Project Condor (Control Multiplayer Spin-off)",
        "Project Eve",
        "Project L (League of Legends Fighting Game)",
        "Project Magnum",
        "Project Mara",
        "Project Re Fantasy",
        "Project Sakura Wars",
        "ProtoCorgi",
        "Protodroid Delta",
        "Psychonauts 2",
        "Pupperazzi",
        "Puyo Puyo Tetris 2",
        "R-Type Final 2",
        "Radio the Universe",
        "Raptor Boyfriend: A High School Romance",
        "Ratchet & Clank Rift Apart",
        "Ratchet & Clank: Rift Apart",
        "Ratchet and Clank PS5 (Unannounced)",
        "Re:Legend",
        "Re:Zero − Starting Life in Another World: The Prophecy of the Throne",
        "Read Only Memories: NEURODIVER",
        "Rebel Galaxy Outlaw",
        "Recompile",
        "Redfall",
        "Redout 2",
        "Relayer",
        "Remnant: From the Ashes",
        "Replaced ",
        "Resident Evil 3",
        "Resident Evil 4 Remake (Rumoured)",
        "Resident Evil 4 VR",
        "Resident Evil 8",
        "Resident Evil Village",
        "Resident Evil: Village DLC ",
        "Retro Machina",
        "RetroMania Wrestling",
        "Returnal",
        "Reverie Knights Tactics",
        "Riders Republic",
        "RiMS Racing",
        "Ring Fit Adventure",
        "Risk of Rain 2",
        "Risk of Rain 2: Survivors of the Void",
        "River City Girls 2",
        "River City Girls",
        "Road 96",
        "Rock of Ages 3: Make & Break",
        "Rocksmith+",
        "Rogue Heroes: Ruins of Tasos ",
        "Rogue Legacy 2",
        "Rogue Lords",
        "Roguebook",
        "Roki",
        "Roller Champions",
        "Root Film",
        "RPG Time: The Legend of Wright",
        "RPGolf Legends ",
        "Ruined King: A League of Legends Story",
        "Rumbleverse",
        "Rumored 2D Metroid Sequel (Unannounced)",
        "Rumored Astrobot Sequel",
        "Rumored Metal Gear Solid Remake (Bluepoint)",
        "Rumored Prince of Persia Remaster",
        "Rumored Splatoon Game (Unannounced)",
        "Rumoured Dead Space Project (EA Motive)",
        "Rumoured Dead Space Sequel (EA Motive)",
        "Rune Factory 5",
        "Ryan's Rescue Squad ",
        "Sable",
        "SacriFire",
        "Saga Frontier Remastered",
        "Saints Row",
        "Sakuna: Of Rice and Ruin",
        "Sakura Wars",
        "Salt and Sacrifice",
        "Sam & Max: This Time It's Virtual",
        "Samurai Gunn 2",
        "Samurai Jack: Battle Through Time",
        "Samurai Shodown",
        "Samurai Warriors 5",
        "Satisfactory",
        "Saturnalia",
        "Say No! More",
        "Sayri: The Beginning",
        "Scarlet Nexus",
        "Scorn",
        "Scott Pilgrim vs. The World: The Game - Complete Edition",
        "ScourgeBringer",
        "Sea of Solitude",
        "Sea of Stars",
        "Sea of Thieves: A Pirate’s Life",
        "Season",
        "Selfloss",
        "Senua's Saga: Hellblade 2",
        "Sephonie",
        "Serial Cleaners",
        "Serious Sam 4: Planet Badass",
        "Serious Sam: Siberian Mayhem",
        "Session",
        "Severed Steel",
        "Shadow Tactics: Blades of the Shogun - Aiko's Choice",
        "Shadow Warrior 3",
        "Shantae and the Seven Sirens",
        "She Dreams Elsewhere",
        "Sherlock Holmes Chapter One",
        "Shin Megami Tensei III: Nocturne HD Remaster",
        "Shin Megami Tensei V",
        "Shovel Knight Dig",
        "Shovel Knight Pocket Dungeon",
        "Shovel Knight: King of Cards",
        "Showa American Story",
        "Shredders",
        "Sifu",
        "Silt",
        "Six Days in Fallujah",
        "SkateBIRD",
        "Skatebird",
        "Skater XL",
        "Skin Deep",
        "Skull & Bones",
        "Skully",
        "Slime Rancher 2",
        "Slipways",
        "Slitterhead ",
        "Sniper Elite 5",
        "Sniper Elite VR",
        "Softly With Teeth",
        "Sol Cresta",
        "Solar Ash",
        "Somerville",
        "Song of Iron",
        "Song of Nunu: A League of Legends Story",
        "Songbird Symphony",
        "Songs of Conquest",
        "Sonic Colors Ultimate",
        "Sonic Frontiers",
        "Sonic Mania 2 (Unannounced)",
        "Sonic Origins",
        "Sons of the Forest",
        "Sonzai",
        "Souldiers",
        "Soulstice",
        "Soundfall",
        "Soup Pot",
        "Source of Madness",
        "Spacebase Startopia",
        "Sparklite",
        "Speed Limit",
        "Spelunky 2",
        "Spider Man: Miles Morales",
        "Spirit Swap: Lo-fi Beats to Match-3 To",
        "Spiritfarer",
        "Splatoon 3",
        "SpongeBob SquarePants: Battle for Bikini Bottom Rehydrated",
        "SpongeBob SquarePants: The Cosmic Shake",
        "Sports Story",
        "Squadron 42 (Star Citizen)",
        "STALKER 2",
        "STALKER 2: Heart of Chernobyl",
        "Star Ocean: The Divine Force",
        "Star Renegades",
        "Star Trek: Resurgence",
        "Star Wars Battlefront 3 (Unannounced)",
        "Star Wars Jedi: Fallen Order Sequel",
        "Star Wars: Eclipse",
        "Star Wars: Hunters",
        "Star Wars: Jedi Fallen Order",
        "Star Wars: Knights of the Old Republic Remake (Unannounced)",
        "Star Wars: Knights of the Old Republic Remake",
        "Star Wars: Squadrons",
        "Star Wars: The Old Republic - Legacy of the Sith",
        "Starfield",
        "Starmancer",
        "Starship Troopers - Terran Command",
        "State of Decay 3",
        "SteamWorld Headhunter",
        "Steel Assault",
        "Steelrising",
        "Stonefly",
        "Stormland",
        "Story of Seasons: Pioneers of Olive Town",
        "Storyteller",
        "Strange Horticulture",
        "Stranger of Paradise: Final Fantasy Origin",
        "Stranger Things 3",
        "Stray Blade",
        "Stray",
        "Street Fighter 6",
        "Streets of Rage 4",
        "Streets of Rage 4: Mr. X Nightmare",
        "Stronghold: Warlords",
        "Subnautica: Below Zero",
        "SuchArt: Genius Artist Simulator",
        "Sucker for Love: First Date",
        "Suicide Squad (Rocksteady)",
        "Suicide Squad: Kill the Justice League",
        "Summer in Mara",
        "Sun Haven",
        "Sunset Overdrive Remaster (Rumored)",
        "Super Magbot",
        "Super Mario 3D All Stars",
        "Super Mario 3D World + Bowser’s Fury",
        "Super Mario Bros. 35",
        "Super Mario Maker 2",
        "Super Mario Odyssey 2 (Unannounced)",
        "Super Mario Sunshine Remaster (Rumored)",
        "Super Meat Boy Forever",
        "Super Mega Baseball 3 ",
        "Super Monkey Ball: Banana Mania",
        "Super Robot Wars 30",
        "Superhot: Mind Control Delete",
        "Surgeon Simulator 2",
        "Swimsanity!",
        "Sword Art Online Alicization Lycoris",
        "Sword of the Necromancer",
        "Syberia: The World Before",
        "Synced Off-Planet",
        "System Shock 2: Enhanced Edition",
        "System Shock",
        "Tactical Breach Wizards",
        "Tails of Iron",
        "Tales of Arise",
        "Tamarindos Freaking Dinner",
        "Tchia",
        "Teardown",
        "Teenage Mutant Ninja Turtles: Shredder’s Revenge",
        "Tekken X Street Fighter",
        "Tell Me Why",
        "Telling Lies",
        "Temtem",
        "Terra Nil",
        "Test Drive Unlimited Solar Crown",
        "Tetris Effect: Connected",
        "The Anacrusis",
        "The Artful Escape",
        "The Ascent",
        "The Big Con",
        "The Binding of Isaac: Repentance",
        "The Blackout Club",
        "The Callisto Protocol",
        "The Captain is Dead",
        "The Cruel King and the Great Hero",
        "The Dark Pictures Anthology: House of Ashes",
        "The Dark Pictures Anthology: The Devil in Me",
        "The Dark Pictures: Man of Medan",
        "The Day Before",
        "The Dungeon Experience",
        "The Elder Scrolls Online: Gates of Oblivion",
        "The Elder Scrolls Online: High Isle",
        "The Elder Scrolls VI",
        "The Elder Scrolls: Blades",
        "The Eternal Cylinder",
        "The Falconeer",
        "The Fermi Paradox",
        "The Forgotten City",
        "The Garden Path",
        "The Good Life",
        "The Great Ace Attorney Chronicles",
        "The Great Ace Attorney Collection (Rumored)",
        "The Gunk",
        "The House of the Dead: Remake",
        "The Invincible",
        "The Iron Oath",
        "The Jackbox Party Pack 8",
        "The King of Fighters XV",
        "The Last Campfire",
        "The Last Clockwinder",
        "The Last Faith",
        "The Last Night",
        """
        The Last of Us ""Remake"
        """,
        "The Last of Us Part II",
        "The Last Spell",
        "The Last Worker ",
        "The Legend of Heroes: Hajimari no Kiseki",
        "The Legend of Heroes: Kuro no Kiseki",
        "The Legend of Heroes: Trails from Zero",
        "The Legend of Tianding",
        "The Legend of Zelda: Breath of the Wild 2",
        "The Legend of Zelda: Skyward Sword HD Remaster (Unannounced)",
        "The Legend of Zelda: Skyward Sword HD",
        "The Magnificent Trufflepigs",
        "The Medium",
        "The Nioh Collection",
        "The Outer Worlds 2",
        "The Outlast Trials",
        "The Pathless",
        "The Pedestrian",
        "The Red Lantern",
        "The Riftbreaker",
        "The Settlers",
        "The Shore",
        "The Sims 4: Cottage Living",
        "The Sinking City",
        "The Stanley Parable: Ultra Deluxe",
        "The Surge 2",
        "The Survivalists",
        "The Talos Principle 2",
        "The Unliving",
        "The Walking Dead: Saints & Sinners - Chapter 2: Retribution",
        "The Waylanders",
        "The Wild at Heart",
        "The Witcher 3: Wild Hunt ( Switch )",
        "The Witcher 3: Wild Hunt (PS5)",
        "The Wolf Among Us 2",
        "The Wolf Among Us Season 2",
        "The Wreck ",
        "There Is No Light",
        "They Always Run",
        "Thirsty Suitors",
        "Thymesia",
        "Tiny Tina’s Wonderlands",
        "Tinykin",
        "TOEM ",
        "TOEM",
        "TOHU",
        "Tokyo Mirage Sessions #FE: Encore",
        "Tom Clancy’s Rainbow Six: Extraction",
        "Tom Clancy’s Rainbow Six: Parasite",
        "Tom Clancy’s Rainbow Six: Quarantine",
        "Tom Clancy’s Splinter Cell Remake",
        "Tom Clancy’s The Division: Heartland",
        "Tom Clancy’s XDefiant",
        "Tony Hawk 3+4 Remake",
        "Tony Hawk Pro Skater 1+2",
        "Torchlight III",
        "Torchlight Infinite",
        "Total War Saga: Troy",
        "Total War: Rome Remastered",
        "Total War: Warhammer 3",
        "Town",
        "Trackmania",
        "Trails of Cold Steel III",
        "Trash Sailors",
        "Trek to Yomi",
        "Trepang2",
        "Trials of Mana",
        "Triangle Strategy",
        "Tribes of Midgard",
        "Trine 4: The Nightmare Prince",
        "Tunche",
        "Tunic",
        "Turbo Overkill",
        "Turnip Boy Commits Tax Evasion",
        "Twelve Minutes",
        "Twin Mirror",
        "Two Point Campus",
        "UFO 50",
        "ULTRAKILL",
        "Ultrawings 2",
        "Unannouced PS5 S.O.C.O.M. Sequel",
        "Unannounced 3D Mario",
        "Unannounced Bloodborne Remaster",
        "Unannounced Call of Duty 2022",
        "Unannounced Ghost Story Games Game",
        "Unannounced Hideo Kojima Title",
        "Unannounced Kingdom Hearts Game",
        "Unannounced Main Series Sonic Game",
        "Unannounced New Silent Hill",
        "Unannounced Next Assassin's Creed",
        "Unannounced Next Tony Hawk Pro Skater Game",
        "Unannounced Spyro the Dragon Game",
        "Unannounced World Rally Championship Game",
        "Unbound: Worlds Apart",
        "Uncharted: Legacy of Thieves",
        "Under Night In-Birth EXE:Late[cl-r]",
        "Undungeon",
        "Unforseen Incidents (Switch)",
        "Unforseen Incidents",
        "Unknown 9: Awakening",
        "Unnanounced Donkey Kong Game",
        "Unpacking",
        "Unreal Life",
        "Untitled Ace Combat game",
        "Untitled Batman Game from WB Games Montréal (Unannounced)",
        "Untitled Final Fantasy XIV Expansion",
        "Untitled Goose Game",
        "Untitled Layers of Fear game",
        "Untitled Machine Games Indiana Jones Game",
        "Untitled Mass Effect sequel",
        "Untitled new Need for Speed",
        "Untitled New TimeSplitters Game",
        "Untitled Open World Star Wars Game (Ubisoft Massive)",
        "Untitled Playdead game",
        "Untitled Respawn Oculus VR FPS",
        "Untitled Skate Sequel",
        "Untitled Wizarding World Game from WB Games",
        "Untitled Yakuza sequel",
        "Utawarerumono: Prelude to the Fallen",
        "Valheim",
        "ValiDate: Struggling Singles in your Area",
        "Valorant ",
        "Vampire: The Masquerade - Blood Hunt",
        "Vampire: The Masquerade - Bloodhunt",
        "Vampire: The Masquerade - Swansong",
        "Vampire: The Masquerade – Bloodlines 2",
        "Venba",
        "Victoria 3",
        "Virgo Vs The Zodiac",
        "Virtua Fighter 5 Ultimate Showdown",
        "Vitamin connection",
        "Vlambeer Arcade with ULTRABUGS",
        "Voice of Cards: The Isle Dragon Roars",
        "Wanderer",
        "Warcraft III: Reforged",
        "Warhammer 40,000: Chaos Gate - Daemonhunters",
        "Warhammer 40,000: Darktide",
        "Warhammer 40,000: Space Marine 2",
        "Warhammer Age of Sigmar: Soul Arena",
        "Warhammer Age of Sigmar: Storm Grounds",
        "WarioWare: Get it Together!",
        "Wartales",
        "Wasteland 3",
        "Wasteland Remastered",
        "Watch Dogs: Legion",
        "Wattam",
        "Way to the Woods",
        "We Are OFK",
        "We Were Here Forever",
        "Weird West",
        "Werewolf: The Apocalypse: Earthblood",
        "Where the Heart Leads",
        "Wild Terra 2: New Lands",
        "Wildermyth",
        "Windbound",
        "Windjammers 2",
        "Witchbrook",
        "Witchfire",
        "Wizard with a Gun",
        "Wolfenstein III",
        "Wolfenstein: Cyberpilot",
        "Wolfenstein: Youngblood",
        "Wonder Boy: Asha in Monster World",
        "Wonderful 101 Remastered",
        "World of Horror",
        "World of Warcraft: Burning Crusade (Classic)",
        "World of Warcraft: Classic",
        "World of Warcraft: Shadowlands",
        "Worms 2020",
        "Worms Rumble",
        "WRATH: Aeon of Ruin",
        "WRC 9",
        "WWE 2K Battlegrounds",
        "WWE 2K22",
        "Wytchwood",
        "X4: Cradle of Humanity",
        "XCOM 3 (Unannounced)",
        "Xenoblade Chronicles: Definitive Edition",
        "XIII (remake)",
        "Yakuza: Like a Dragon",
        "Yes, Your Grace",
        "Yo-kai Watch 4",
        "Yooka-Laylee and the Impossible Lair",
        "You Suck At Parking",
        "Ys IX: Monstrum Nox",
        "Yu-Gi-Oh! Master Duel",
        "Yurukill: The Calumniation Games",
        "Zombie Army 4"
    ];
}
