namespace FantasyCritic.DatabaseUpdater.CodeMigrations;

internal static class ProcessSetCleanupResources
{
    //'Star Wars: Squadrons' and 'Project Maverick (Unannounced Star Wars)' were separate master games when these bids were
    //placed and were merged afterwards, so the bid looks contested but wasn't.
    public static IReadOnlySet<Guid> BidsWithNoRealCompetition { get; } = new HashSet<Guid>
    {
        Guid.Parse("907dacab-e1fe-4a70-9103-8c114c6490eb")
    };

    public static Dictionary<string, List<string>> OldGameNameMappings { get; } = new Dictionary<string, List<string>>()
        {
            {"Animal Crossing: New Horizons", ["Animal Crossing"]},
            {"Pokémon Sword and Shield", ["Pokemon Gen 8"]},
            {"Star Wars: Jedi Fallen Order", ["Star Wars Jedi: Fallen Order", "Star Wars:Jedi Fallen Order"]},
            {"Dying Light 2: Stay Human", ["Dying Light 2"]},
            {"Warcraft III: Reforged", ["Warcraft 3: Reforged"]},
            {"Metroid Prime 4: Beyond", ["Metroid Prime 4"]},
            {"Skull and Bones", ["Skull & Bones"]},
            {"Final Fantasy VII Remake", ["Final Fantasy 7 Remake"]},
            {"Little Town Hero", ["Town"]},
            {"APE OUT", ["Ape Out"]},
            {"The Dark Pictures: Man of Medan", ["Man of Medan"]},
            {"Marvel Ultimate Alliance 3: The Black Order", ["Marvel Ultimate Alliance 3"]},
            {"The Settlers: New Allies", ["The Settlers"]},
            {"SteamWorld Quest: Hand of Gilgamech", ["Steamworld Quest"]},
            {"Call of Duty: Modern Warfare (2019)", ["Call of Duty 2019"]},
            {"Dragon Ball Z Kakarot", ["Dragon Ball ‘Project Z’", "Dragonball Z Kakarot"]},
            {"Super Mario Maker 2", ["Super Mario Maker 2 (Unannounced)"]},
            {"Pikmin 4", ["Pikmin 4 (Unannounced)"]},
            {"Celeste: Farewell", ["Celeste DLC"]},
            {"Dead By Daylight (Switch)", ["Dead By Daylight"]},
            {"Chicory: A Colorful Tale", ["Drawdog"]},
            {"Trine 4: The Nightmare Prince", ["Trine 4"]},
            {"Solar Ash", ["Solar Ash Kingdom"]},
            {"GRID Autosport (Switch)", ["GRID Autosport"]},
            {"The Red Lantern", ["Red Lantern"]},
            {"Persona 5 Royal", ["Persona 5 The Royal"]},
            {"Power Rangers: Battle for the Grid", ["Power Raners: Battle for the Grid"]},
            {"Watch Dogs: Legion", ["Watch Dogs 3 (Unannounced)"]},
            {"ULTRABUGS", ["Vlambeer Arcade with ULTRABUGS"]},
            {"Shantae and the Seven Sirens (Console/PC)", ["Shantae 5", "Shantae and the Seven Sirens"]},
            {"Darkwood (Console)", ["Darkwood"]},
            {"Splitgate", ["Splitgate Arena Warfare "]},
            { "HuniePop 2: Double Date", ["HuniePop 2"] },
            { "Baldo: The Guardian Owls", ["Baldo"] },
            { "Brave Earth: Prologue", ["Brave Earth - Prologue"] },
            { "Disney Tsum Tsum Festival", ["Disney Tsum Tsum"] },
            { "The Witcher 3: Wild Hunt (Switch)", ["The Witcher 3: Wild Hunt ( Switch )"] },
            { "Spirit Hunter: NG", ["NG"] },
            { "Medal of Honor: Above and Beyond", ["Untitled Respawn Oculus VR FPS"] },
            { "One Finger Death Punch 2 (Switch)", ["One Finger Death Punch 2"] },
            { "Paper Beast", ["Paper Beasts"] },
            { "The Legend of Zelda: Tears of the Kingdom", ["The Legend of Zelda: Breath of the Wild 2"] },
            { "Senua's Saga: Hellblade II", ["Senua's Saga: Hellblade 2"] },
            { "Horizon Forbidden West", ["Horizon: Zero Dawn Sequel (Unannounced)"] },
            { "Diablo IV", ["Diablo 4"] },
            { "Persona 5 Strikers", ["Persona 5 Scramble: The Phantom Strikers"] },
            { "Vampire: The Masquerade - Bloodlines 2", ["Vampire: The Masquerade – Bloodlines 2"] },
            { "The Wolf Among Us 2", ["The Wolf Among Us Season 2"] },
            { "Immortals: Fenyx Rising", ["Gods & Monsters"] },
            { "12 Minutes", ["Twelve Minutes"] },
            { "Tom Clancy’s Rainbow Six: Extraction", ["Tom Clancy’s Rainbow Six: Parasite", "Tom Clancy’s Rainbow Six: Quarantine"] },
            { "Dr. Kawashima’s Brain Training", ["Dr Kawashima's Brain Training (Brain Age) for Nintendo Switch"] },
            { "Assassin's Creed Valhalla", ["Assassin's Creed 2020 (Unannounced)"] },
            { "Tokyo Mirage Sessions ♯FE: Encore", ["Tokyo Mirage Sessions #FE: Encore"] },
            { "Call of Duty: Black Ops Cold War", ["Call of Duty 2020 (Unannounced)"] },
            { "Forza Motorsport", ["Forza Motorsport (Xbox Series X)", "Forza Motorsport 8 (Unannounced)"] },
            { "SkateBIRD", ["Skatebird"] },
            { "Fable", ["Fable (Unannounced)", "Fable (Xbox Series X)"] },
            { "Impostor Factory", ["Imposter Factory"] },
            { "Iron Harvest", ["Iron harvest "] },
            { "Gotham Knights", ["Untitled Batman Game from WB Games Montréal (Unannounced)"] },
            { "Paper Mario: The Origami King", ["Paper Mario Sequel (Unannounced)"] },
            { "Demon's Souls (2020)", ["Demon Souls Remake", "Demon Souls Remake (Unannounced) "] },
            { "Sakura Wars", ["Project Sakura Wars"] },
            { "Deltarune Chapter 2", ["Deltarune"] },
            { "Grand Theft Auto VI", ["Grand Theft Auto 6 (Unannounced)"] },
            { "Metroid Dread", ["Rumored 2D Metroid Sequel (Unannounced)"] },
            { "Gran Turismo 7", ["Gran Turismo Sequel (Unannounced)"] },
            { "Ratchet & Clank: Rift Apart", ["Ratchet & Clank Rift Apart", "Ratchet and Clank PS5 (Unannounced)"] },
            { "Mario Kart World", ["Mario Kart (Unannounced Next Mainline Console Game)", "Mario Kart 9 (Unannounced)"] },
            { "Hogwarts Legacy", ["Harry Potter (Unannounced WB Games)", "Untitled Wizarding World Game from WB Games"] },
            { "Command & Conquer Remastered Collection", ["Command & Conquer Remastered"] },
            { "Call of Duty: Modern Warfare 2 Remastered", ["Modern Warfare 2 Remastered (Unannounced)"] },
            { "Crysis Remastered (Switch)", ["Crysis Remastered"] },
            { "Super Mario Sunshine Remaster (Deprecated)", ["Super Mario Sunshine Remaster (Rumored)"] },
            { "Werewolf: The Apocalypse - Earthblood", ["Werewolf: The Apocalypse: Earthblood"] },
            { "Dungeons & Dragons: Dark Alliance", ["Dark Alliance"] },
            { "Hitman 3", ["Hitman 3 (Partially Announced)"] },
            { "Gestalt: Steam & Cinder", ["Gestalt Steam and Cinder"] },
            { "New Mainline Banjo Kazooie (Unannounced)", ["New Banjo Kazooie  (Unannounced)"] },
            { "Destruction Allstars", ["Destruction Allstars "] },
            { "Resident Evil Village", ["Resident Evil 8"] },
            { "Hyper Scape", ["Hyper Scape (Rumored)"] },
            { "Far Cry 6", ["Far Cry 6 (Unannounced)"] },
            { "Blue Protocol: Star Resonance", ["Blue Protocol"] },
            { "Worms Rumble", ["Worms 2020"] },
            { "Bright Memory: Infinite", ["Bright Memory infinite"] },
            { "Suicide Squad: Kill the Justice League", ["Suicide Squad (Rocksteady)"] },
            { "Prince of Persia: The Sands of Time Remake", ["Rumored Prince of Persia Remaster"] },
            { "Super Mario 3D All-Stars", ["Super Mario 3D All Stars"] },
            { "Cyanide & Happiness: Freakpocalypse", ["Freakpocalypse: The Cyanide & Happiness Adventure Game"] },
            { "Balan Wonderworld", ["BALAN WONDERWORLD"] },
            { "Ark 2", ["Ark II"] },
            { "Dragon Age: The Veilguard", ["Dragon Age 4"] },
            { "Battlefield 2042", ["Next Gen Battlefield Game"] },
            { "Season: A Letter to the Future", ["Season"] },
            { "Monster Hunter Rise", ["MONSTER HUNTER RISE"] },
            { "Final Fantasy XVI", ["Final Fantasy XVI "] },
            { "The Forgotten City", ["Forgotten City"] },
            { "The Lord of the Rings: Gollum", ["Lord of the Rings: Gollum"] },
            { "STALKER 2: Heart of Chornobyl", ["STALKER 2", "STALKER 2: Heart of Chernobyl"] },
            { "Forza Horizon 5", ["Forza Horizon 5 (Unannounced)"] },
            { "Rumored Metal Gear Solid 1 Remake (Unannounced)", ["Rumored Metal Gear Solid Remake (Bluepoint)"] },
            { "Final Fantasy XIV: Endwalker", ["Untitled Final Fantasy XIV Expansion"] },
            { "Unannounced New Mainline Ace Attorney Game", ["Phoenix Wright: Ace Attorney 7"] },
            { "Spyro: A Realm Beyond", ["Unannounced Spyro the Dragon Game"] },
            { "Pokémon Brilliant Diamond & Shining Pearl", ["Pokemon Diamond and Pearl Remake (Unannounced)"] },
            { "The Last of Us Multiplayer Game", ["Last of Us Factions 2"] },
            { "Ghosts ‘n Goblins: Resurrection", ["Ghost ‘n Goblins: Resurrection"] },
            { "Warhammer Age of Sigmar: Storm Ground", ["Warhammer Age of Sigmar: Storm Grounds"] },
            { "Call of Duty Vanguard", ["Call of Duty 2021"] },
            { "The Great Ace Attorney Chronicles", ["The Great Ace Attorney Collection (Rumored)"] },
            { "Path of Exile 2", ["Path of Exile II"] },
            { "The Legend of Zelda: Skyward Sword HD", ["The Legend of Zelda: Skyward Sword HD Remaster (Unannounced)"] },
            { "Sonic Frontiers", ["Unannounced Main Series Sonic Game"] },
            { "Astro Bot", ["Rumored Astrobot Sequel"] },
            { "AEW: Fight Forever", ["All Elite Wrestling: The Game"] },
            { "The Elder Scrolls Online: Blackwood", ["The Elder Scrolls Online: Gates of Oblivion"] },
            { "God of War: Ragnarök", ["God of War: Ragnarok"] },
            { "Figment 2: Creed Valley", ["Figment: Creed Valley"] },
            { "Fire Emblem: Genealogy of the Holy War Re-Something (Unannounced)", ["Fire Emblem: Geneaology of the Holy War Remake (Unannounced)"] },
            { "007 First Light", ["Project 007 (IO Interactive)"] },
            { "Pokémon Let's Go 2 (Unannounced)", ["Pokemon Let's Go 2 (Unannounced)"] },
            { "Final Fantasy VII Rebirth", ["Final Fantasy VII Remake Part 2"] },
            { "Splatoon 3", ["Rumored Splatoon Game (Unannounced)"] },
            { "Fire Emblem Engage", ["New Fire Emblem Game (Unannounced)", "New Fire Emblem Game (Unnanounced)"] },
            { "Re:ZERO -Starting Life in Another World- The Prophecy of the Throne", ["Re:Zero − Starting Life in Another World: The Prophecy of the Throne"] },
            { "Indiana Jones and the Great Circle", ["Untitled Machine Games Indiana Jones Game"] },
            { "eFootball", ["PES 2022"] },
            { "Endling - Extinction is Forever", ["Endling"] },
            { "Protodroid DeLTA", ["Protodroid Delta"] },
            { "skate.", ["Untitled Skate Sequel"] },
            { "Stellar Blade", ["Project Eve"] },
            { "Metaphor: ReFantazio", ["Project Re Fantasy"] },
            { "The Legend of Heroes: Trails into Reverie", ["The Legend of Heroes: Hajimari no Kiseki"] },
            { "Resident Evil 4 Remake", ["Resident Evil 4 Remake (Rumoured)"] },
            { "Cosmodread", ["Cosmophobia"] },
            { "Forspoken", ["Project Athia"] },
            { "Diablo II Resurrected", ["Diablo II Remake"] },
            { "Demon Slayer - Kimetsu no Yaiba - The Hinokami Chronicles", ["Demon Slayer: Kimetsu no Yaiba – Hinokami Kepputan", "Kimetsu no Yaiba: Hinokami Keppuutan"] },
            { "Star Wars Jedi: Survivor", ["Star Wars Jedi: Fallen Order Sequel"] },
            { "Kingdom Come: Deliverance II", ["Kingdom Come: Deliverance 2 (Unannounced)"] },
            { "Mario + Rabbids: Sparks of Hope", ["Mario and Rabbids Sequel (Unannounced)"] },
            { "2XKO", ["Project L (League of Legends Fighting Game)"] },
            { "EA Sports College Football 25", ["NCAA Football Reboot"] },
            { "Untitled Playdead Game", ["Untitled Playdead game"] },
            { "Amid Evil: The Black Labyrinth", ["Amid Evil: The Black Labrynth"] },
            { "Shin-Chan: Me and the Professor on Summer Vacation", ["Crayon Shin-Chan"] },
            { "Aliens: Fireteam Elite", ["Aliens: Fireteam"] },
            { "Life is Strange: True Colors", ["Life is Strange 3"] },
            { "Star Wars Outlaws", ["Untitled Open World Star Wars Game (Ubisoft Massive)"] },
            { "Undisputed", ["eSports Boxing Club"] },
            { "OXENFREE II: Lost Signals", ["Oxenfree 2: Lost Signals"] },
            { "Star Wars: Knights of the Old Republic Remake", ["Star Wars: Knights of the Old Republic Remake (Unannounced)"] },
            { "Lost Judgment", ["Judgment Sequel (Rumored)"] },
            { "Phasmophobia", ["Phasmaphobia"] },
            { "KitHack Model Club", ["Balsa Model Flight Simulator"] },
            { "Donkey Kong Bananza", ["Unnanounced Donkey Kong Game"] },
            { "The Legend of Heroes: Trails through Daybreak", ["The Legend of Heroes: Kuro no Kiseki"] },
            { "Stranger of Paradise: Final Fantasy Origin", ["Final Fantasy Origin"] },
            { "Dragon Quest III HD-2D Remake", ["Dragon Quest III HD-2D"] },
            { "Dragon Quest XII: Beyond Dreams", ["Dragon Quest XII: The Flames of Fate"] },
            { "Xenoblade Chronicles 3", ["New Xenoblade Game (Unannounced)"] },
            { "Marvel’s Midnight Suns", ["Marvel XCOM Style Game"] },
            { "TOEM ", ["TOEM"] },
            { "Vampire: The Masquerade - Bloodhunt", ["Vampire: The Masquerade - Blood Hunt"] },
            { "Advance Wars 1+2: Re-Boot Camp", ["Advance Wars 1 + 2: Re-boot Camp"] },
            { "Ghost of Tsushima Director's Cut", ["Ghost of Tsushima Standalone Expansion (Rumoured)"] },
            { "Dead Space (Remake)", ["Rumoured Dead Space Project (EA Motive)", "Rumoured Dead Space Sequel (EA Motive)"] },
            { "NEEDY STREAMER OVERLOAD", ["NEEDY GIRL OVERDOSE"] },
            { "XDefiant", ["Tom Clancy’s XDefiant"] },
            { "Grand Theft Auto: The Trilogy – The Definitive Edition", ["Grand Theft Auto Remastered"] },
            { "Breakwaters: Crystal Tides", ["Breakwaters"] },
            { "Firegirl: Hack 'n Splash Rescue", ["Firegirl"] },
            { "Stray Gods: The Roleplaying Musical", ["Chorus: An Adventure Musical"] },
            { "Replaced", ["Replaced "] },
            { "Judas", ["Unannounced Ghost Story Games Game"] },
            { "F1 22", ["F1 2022"] },
            { "Call of Duty: Modern Warfare II", ["Unannounced Call of Duty 2022"] },
            { "Slitterhead", ["Slitterhead "] },
            { "Maximum Action", ["MAXIMUM ACTION"] },
            { "Velvet Bite: Softly, with Teeth", ["Softly With Teeth"] },
            { "Towerborne", ["Project Belfry (Stoic)"] },
            { "Kingdom Hearts IV", ["Unannounced Kingdom Hearts Game"] },
            { "Gears of War: E-Day", ["Gears 6 (Unannounced)"] },
            { "Unforseen Incidents (Switch)", ["Unforseen Incidents"] },
            { "Sunset Overdrive Remaster (Unannounced)", ["Sunset Overdrive Remaster (Rumored)"] },
            { "Tony Hawk's Pro Skater 3 + 4", ["Tony Hawk 3+4 Remake", "Unannounced Next Tony Hawk Pro Skater Game"] },
            { "Persona 6", ["Persona 6 (Unannounced)"] },
            { "Goldeneye (Xbox One Re-Release)", ["Goldeneye (Rumored Rerelease)"] },
            { "Loco Motive", ["Loco Motive "] },
            { "Like a Dragon: Infinite Wealth", ["Untitled Yakuza sequel"] },
            { "The Witcher 3: Wild Hunt (PS5/Xbox Series)", ["The Witcher 3: Wild Hunt (PS5)"] },
            { "FrighTV Presents GHOSTS", ["Ghosts"] },
            { "Chrono Cross: The Radical Dreamers Edition", ["Chrono Cross Remaster (Unannounced) "] },
            { "Metal Gear Solid Δ: Snake Eater", ["Metal Gear Solid Snake Eater Remake (Unannounced)"] },
            { "Pokémon Scarlet & Violet", ["Pokémon Generation 9"] },
            { "The First Descendant", ["Project Magnum"] },
            { "SYNCED", ["Synced Off-Planet"] },
            { "Death Stranding Director's Cut (PC) ", ["Death Stranding Directors Cut (PC) "] },
            { "EA Sports PGA Tour", ["EA Sports PGA TOUR (2022)"] },
            { "Ace Combat 8: Wings of Theve", ["Untitled Ace Combat game"] },
            { "Grand Theft Auto V (PS5 & Xbox Series)", ["Grand Theft Auto V (PS5)"] },
            { "Deep Rock Galactic (Playstation Port)", ["Deep Rock Galactic (Console)"] },
            { "Torchlight: Infinite", ["Torchlight Infinite"] },
            { "Metroid Prime Remastered", ["Metroid Prime 1 HD (Unannounced)"] },
            { "Detective Pikachu Returns", ["Detective Pikachu Sequel (Unannounced)"] },
            { "Armored Core VI: Fires of Rubicon", ["Armored Core 6"] },
            { "Dragon's Dogma 2", ["Dragon's Dogma 2 (Unannounced)"] },
            { "Deltarune", ["Deltarune (Full Release)"] },
            { "Lakeburg Legacies", ["Lakebury Legacies"] },
            { "Plants vs. Zombies 3: Welcome to Zomburbia", ["Plants vs Zombies 3"] },
            { "Park Beyond", ["Park Beyond "] },
            { "Marvel's Wolverine", ["Marvel’s Wolverine"] },
            { "Need for Speed Unbound", ["Untitled new Need for Speed"] },
            { "Resident Evil Village - Winters' Expansion", ["Resident Evil: Village DLC "] },
            { "Just Dance 2023 Edition", ["Just Dance 23"] },
            { "System Shock 2: 25th Anniversary Remaster", ["System Shock 2: Enhanced Edition"] },
            { "F1 Manager 2022", ["F1 Management Game"] },
            { "FBC: Firebreak", ["Project Condor (Control Multiplayer Spin-off)"] },
            { "Layers of Fear", ["Untitled Layers of Fear game"] },
            { "Unannouced New S.O.C.O.M. Game", ["Unannouced PS5 S.O.C.O.M. Sequel"] },
            { "The Wreck", ["The Wreck "] },
            { "The Last Worker", ["The Last Worker "] },
            { "Mortal Kombat 1", ["Mortal Kombat 12 (Unannounced)"] },
            { "Amnesia: Rebirth", ["Next Frictional Game"] },
            { "Unannounced Mainline 3D Mario Platformer", ["Unannounced 3D Mario", "Super Mario Odyssey 2 (Unannounced)"] },
            { "Football Manager 2022", ["Football Manager (2021)"] },
            { "Silent Hill f", ["Unannounced New Silent Hill"] },
            { "Gwent: Rogue Mage", ["Project Golden Nekker"] },
            { "Assassin's Creed Infinity", ["Unannounced Next Assassin's Creed"] },
            { "The Last of Us Part I", ["""
                                        The Last of Us "Remake"
                                        """] },
            { "gen ATLAS", ["GenDesign's Untitled New Game"] },
            { "Ashigaru: The Last Shogun", ["Next Gilson B Pontes Game"] },
            { "OD (Hideo Kojima Game)", ["Unannounced Hideo Kojima Title"] },
            { "WRC Generations", ["Unannounced World Rally Championship Game"] },
            { "World's End Club", ["Death March Club"] },
            { "Songs of Conquest", ["Song of Conquest"] },
            { "Evolutis: Duality", ["Evolutis"] },
            { "XCOM: Chimera Squad", ["XCOM 3 (Unannounced)"] },
            { "Pikmin 3 Deluxe", ["Pikmin 3 (Unannounced Switch Port)"] },
            { "Star Wars: Squadrons", ["Project Maverick (Unannounced Star Wars)"] },
            { "Super Mario Galaxy Remaster (Deprecated)", ["Super Mario Galaxy Remaster (Rumored)"] },
            { "Mass Effect: Legendary Edition", ["Mass Effect Remaster (Unannounced)"] },
            { "Destiny 2: Beyond Light", ["Destiny 2 DLC expansion (Unannounced)"] },
            { "NEO: The World Ends with You", ["The World Ends With You 2 (Unannounced) "] },
            { "Café Enchanté", ["Cafe Enchante"] },
            { "LOVE - A Puzzle Box Filled with Stories", ["LOVE - A Puzzle Box Full of Stories"] },
        };
}
