export interface MasterGameYear {
  masterGameID: string;
  year: number;
  gameName: string;
  estimatedReleaseDate: string;
  minimumReleaseDate: string;
  maximumReleaseDate: string;
  earlyAccessReleaseDate: string | null;
  internationalReleaseDate: string | null;
  announcementDate: string | null;
  releaseDate: string | null;
  isReleased: boolean;
  releasingToday: boolean;
  willRelease: boolean;
  delayContention: boolean;
  showNote: boolean;
  criticScore: number | null;
  fantasyPoints: number | null;
  averagedScore: boolean;
  notes: string | null;
  openCriticID: number | null;
  openCriticSlug: string | null;
  gGToken: string | null;
  gGSlug: string | null;
  subGames: MasterGameYear[] | null;
  tags: string[];
  readableTags: string[];
  boxartFileName: string | null;
  gGCoverArtFileName: string | null;
  addedTimestamp: string;
  syncWithExternalAPIs: boolean;
  useSimpleEligibility: boolean;
  percentStandardGame: number;
  percentCounterPick: number;
  eligiblePercentStandardGame: number;
  adjustedPercentCounterPick: number | null;
  averageDraftPosition: number | null;
  hypeFactor: number;
  dateAdjustedHypeFactor: number;
  peakHypeFactor: number;
  projectedFantasyPoints: number;
  projectedOrRealFantasyPoints: number;
}
