global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using CSharpFunctionalExtensions;
global using FantasyCritic.Lib.Domain;
global using FantasyCritic.Lib.Enums;
global using NodaTime;
